version: "3.8"

services:
  n8n:
    image: n8nio/n8n:1.114.3
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - ./.n8n-data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_TELEGRAM_APPEND_ATTRIBUTION=false
      - WEBHOOK_URL=SUA-URL-NGROK

    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=SUA-KEY-AQUI
    ports:
      - 4040:4040
    depends_on:
      - n8n
    restart: always
